---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  #no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy the VM
      virt_lightning.virt_lightning.vm:
        name: myvm
        state: absent
